### ISSUE TITLE
Source codes and datasets are missing

### ISSUE THREAD

**Issue by as4mz** [robot-learning-freiburg/MM-DistillNet#1]
Hi,

I have tried to run the following code:
`python train.py --config ./configs`
 
Then, got the following error:
ModuleNotFoundError: No module named 'src.fullcnn_net'.

After checking the utils.py, I feel the followings source files are missing:

src.fullcnn_net
src.loss.ABLoss 
src.loss.MTALoss 
src.loss.KLLoss
src.loss.GroupAttentionLoss 
src.loss.MultiTeacherPairWiseSimilarityLoss  src.loss.MultiTeacherPairWiseSimilarityLoss
src.loss.MultiTeacherContrastiveAttentionLoss 
src.loss. MultiTeacherContrastiveAttentionLoss
src.loss.MultiTeacherTrippletAttentionLoss 
src.loss. MultiTeacherTrippletAttentionLoss
src.loss.CRDLoss import CRDLoss
src.loss.NSTLoss 
src.loss.PKTLoss 
src.loss.SimilarityLoss 
src.loss.RankingLoss

Also, I am not sure how to download/access the datasets. I do not see any binary files downloaded inside the folder. 

Thanks for your help.

**Comment by avalada** [comment]
Should be fixed.
