### ISSUE TITLE
question in Evaluate

### ISSUE THREAD

**Issue by muzhaohui** [robot-learning-freiburg/MM-DistillNet#10]
Hello there!

First of all, thank you for your outstanding work! I have a problem when reproducing your work. 

Your GT is generated through the teacher network, so when the teacher network performance changes, then the GT will change accordingly. Do you have a more accurate GT? Or can you teach me how to measure the performance of the student model more accurately?

Thanks!

**Comment by avalada** [comment]
You may have misunderstood the goal of the approach. The teachers are first trained with GT data on disjoint modality-specific datasets. Then the student is trained to match the predictions of the teacher. Paired GT data for the teacher and the student is not available. If you have paired GT labels for the teacher and the student then there is no point using knowledge distillation for this case, you can just train the student on the GT directly without any teacher.
