### ISSUE TITLE
Question in Evaluate

### ISSUE THREAD

**Issue by muzhaohui** [robot-learning-freiburg/MM-DistillNet#11]
Hello there!
First of all, thank you for your outstanding work! I have a problem when reproducing your work.

I'm use the following command to evaluate.
python evaluate.py --config configs/mm-distillnet.cfg --checkpoint trained_models/mm-distillnet.0.pth.tar

But get bad performance.Can you help me how to improve?
![image](https://user-images.githubusercontent.com/33193619/126589428-a0e8d2a9-ce4c-40c3-b98f-fe9dea2ea364.png)

![image](https://user-images.githubusercontent.com/33193619/126589394-167a5ec1-9afc-4e52-97c9-a4f9febb78a6.png)

Thanks!

**Comment by sunwell1994** [comment]
same problem here. Do you use the given version of python, Pytorch, and Cuda? My version is a bit different, but it should not degrade the performance so much during inference.

**Comment by muzhaohui** [comment]
> 同样的问题在这里。您是否使用给定版本的 python、Pytorch 和 Cuda？我的版本有点不同，但它不应该在推理过程中降低性能。

I found that the cause of the problem was the thermal teacher, because there was basically no output during the test. And the provided model cannot be fully imported when importing. I feel that the author’s thermal teacher model may not be EfficientDet_D2 in the code.
#15

**Comment by sunwell1994** [comment]
> > 同样的问题在这里。您是否使用给定版本的 python、Pytorch 和 Cuda？我的版本有点不同，但它不应该在推理过程中降低性能。
> 
> I found that the cause of the problem was the thermal teacher, because there was basically no output during the test. And the provided model cannot be fully imported when importing. I feel that the author’s thermal teacher model may not be EfficientDet_D2 in the code.
> #15

Are teacher models called during inference? I thought that teacher models are used during training to generate labels and only the audio regression model will be used for inference.

**Comment by catherine-qian** [comment]
hi, can I know your dataset structure?


Because from the readme, it should contains 50 directories with “ We split the data using a 60 (train) /20 (validation)/20 (test) scheme, which can be found under the `SPLITS` directory”:
http://multimodal-distill.cs.uni-freiburg.de/static/dist/MAVD_dataset/README.txt?

When I download the dataset, I only get 12 directories with the following structures:
432K	drive_day_2020_03_18_15_42_58
53M	drive_day_2020_04_14_14_33_17
314M	drive_day_2020_04_14_15_10_13
173M	drive_day_2020_04_14_15_20_14
202M	drive_day_2020_04_14_16_16_27
862M	drive_day_2020_04_21_15_48_20
488M	drive_day_2020_04_21_15_58_22
2.6G	drive_day_2020_05_21_20_55_36
5.6G	drive_night_2020_05_21_21_05_38
7.1G	drive_night_2020_05_21_22_22_50
11G	drive_night_2020_05_31_22_00_00
104M	drive_night_2020_05_31_22_23_23

**Comment by eyeris** [comment]
@muzhaohui May I know how did you make it runnable?
I used the same method but end up getting this.
![image](https://user-images.githubusercontent.com/4762674/143425541-3102fccd-67d1-475e-849c-530105ab97df.png)

Also, I have the following issue as well. Tried to reach the authors in many ways but didn't have any reply. 
https://github.com/robot-learning-freiburg/MM-DistillNet/issues/18

**Comment by muzhaohui** [comment]
> @muzhaohui May I know how did you make it runnable? I used the same method but end up getting this. ![image](https://user-images.githubusercontent.com/4762674/143425541-3102fccd-67d1-475e-849c-530105ab97df.png)
> 
> Also, I have the following issue as well. Tried to reach the authors in many ways but didn't have any reply. #18

1. Check if there is any problem with the path
2. If it doesn't work, delete the offending data

**Comment by liushibei** [comment]
Have you solved this problem?
The performance of the model I trained is very poor
![6（1）](https://user-images.githubusercontent.com/50077262/160550444-460336fa-74c4-4cb4-b366-4b616c9b6ffd.png)

The performance of the model provided by article are also very poor.
![evaluate](https://user-images.githubusercontent.com/50077262/160550470-6c195e45-0851-4e64-b39b-3c28acf1b742.PNG)

**Comment by RST2detection** [comment]
> Have you solved this problem? The performance of the model I trained is very poor ![6（1）](https://user-images.githubusercontent.com/50077262/160550444-460336fa-74c4-4cb4-b366-4b616c9b6ffd.png)
> 
> The performance of the model provided by article are also very poor. ![evaluate](https://user-images.githubusercontent.com/50077262/160550470-6c195e45-0851-4e64-b39b-3c28acf1b742.PNG)

May I ask if you have solved this problem? Whether I retrain or test using the best model given by the author, the results are nowhere near the accuracy reported in the article.
