### ISSUE TITLE
Something wrong with the dataset download path

### ISSUE THREAD

**Issue by zhouweii234** [robot-learning-freiburg/MM-DistillNet#7]
I want to download the dataset, but an error occurred
`HTTP request sent, awaiting response... 502 Bad Gateway`
`2021-05-20 00:49:02 ERROR 502: Bad Gateway.`

The URL of the dataset `http://multimodal-distill.cs.uni-freiburg.de/#dataset` also cannot be opened.
![image](https://user-images.githubusercontent.com/62086490/118904608-cc3af100-b94c-11eb-97c7-a1d13149cec8.png)

Could you fix this problem？

**Comment by avalada** [comment]
Please try now
